<?php

namespace Database\Seeders;

use App\Models\Campus;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CampusSeeder extends Seeder
{
    public function run(): void
    {
        $campuses = [
            [
                'name' => 'Career Institute Lahore',
                'title' => 'Career Institute Lahore',
                'slug' => 'career-institute-lahore',
                'code' => 'CILHR01',
                'country' => 'Pakistan',
                'city' => 'Lahore',
                'city_abbr' => 'LHR',
                'campus_type' => 'company',
                'campus_email' => 'lahore@career.test',
                'landline' => '042-3000-1001',
                'mobile' => '0300-0001001',
                'address' => 'Johar Town, Lahore',
                'labs_count' => 5,
                'royalty_rate' => null,
                'status' => 'active',
                'remarks' => 'Demo company campus',
            ],
            [
                'name' => 'Career Institute Faisalabad',
                'title' => 'Career Institute Faisalabad',
                'slug' => 'career-institute-faisalabad',
                'code' => 'CIFSD01',
                'country' => 'Pakistan',
                'city' => 'Faisalabad',
                'city_abbr' => 'FSD',
                'campus_type' => 'company',
                'campus_email' => 'faisalabad@career.test',
                'landline' => '041-3000-1002',
                'mobile' => '0300-0001002',
                'address' => 'D Ground, Faisalabad',
                'labs_count' => 4,
                'royalty_rate' => null,
                'status' => 'active',
                'remarks' => 'Demo company campus',
            ],
            [
                'name' => 'Career Franchise Gujranwala',
                'title' => 'Career Franchise Gujranwala',
                'slug' => 'career-franchise-gujranwala',
                'code' => 'CIGJW01',
                'country' => 'Pakistan',
                'city' => 'Gujranwala',
                'city_abbr' => 'GJW',
                'campus_type' => 'franchise',
                'campus_email' => 'gujranwala.franchise@career.test',
                'landline' => '055-3000-2001',
                'mobile' => '0301-0002001',
                'address' => 'Satellite Town, Gujranwala',
                'labs_count' => 3,
                'royalty_rate' => 20.00,
                'status' => 'active',
                'remarks' => 'Demo franchise with 20% royalty',
            ],
            [
                'name' => 'Career Franchise Sialkot',
                'title' => 'Career Franchise Sialkot',
                'slug' => 'career-franchise-sialkot',
                'code' => 'CISKT01',
                'country' => 'Pakistan',
                'city' => 'Sialkot',
                'city_abbr' => 'SKT',
                'campus_type' => 'franchise',
                'campus_email' => 'sialkot.franchise@career.test',
                'landline' => '052-3000-2002',
                'mobile' => '0301-0002002',
                'address' => 'Cantt Area, Sialkot',
                'labs_count' => 2,
                'royalty_rate' => 20.00,
                'status' => 'active',
                'remarks' => 'Demo franchise with 20% royalty',
            ],
            [
                'name' => 'Career Institute Islamabad',
                'title' => 'Career Institute Islamabad',
                'slug' => 'career-institute-islamabad',
                'code' => 'CIISB01',
                'country' => 'Pakistan',
                'city' => 'Islamabad',
                'city_abbr' => 'ISB',
                'campus_type' => 'company',
                'campus_email' => 'islamabad@career.test',
                'landline' => '051-3000-1003',
                'mobile' => '0300-0001003',
                'address' => 'Blue Area, Islamabad',
                'labs_count' => 4,
                'royalty_rate' => null,
                'status' => 'active',
                'remarks' => 'Demo company campus',
            ],
            [
                'name' => 'Career Institute Karachi',
                'title' => 'Career Institute Karachi',
                'slug' => 'career-institute-karachi',
                'code' => 'CIKHI01',
                'country' => 'Pakistan',
                'city' => 'Karachi',
                'city_abbr' => 'KHI',
                'campus_type' => 'company',
                'campus_email' => 'karachi@career.test',
                'landline' => '021-3000-1004',
                'mobile' => '0300-0001004',
                'address' => 'Shahrah-e-Faisal, Karachi',
                'labs_count' => 5,
                'royalty_rate' => null,
                'status' => 'active',
                'remarks' => 'Demo company campus',
            ],
            [
                'name' => 'Career Franchise Multan',
                'title' => 'Career Franchise Multan',
                'slug' => 'career-franchise-multan',
                'code' => 'CIMUL01',
                'country' => 'Pakistan',
                'city' => 'Multan',
                'city_abbr' => 'MUL',
                'campus_type' => 'franchise',
                'campus_email' => 'multan.franchise@career.test',
                'landline' => '061-3000-2003',
                'mobile' => '0301-0002003',
                'address' => 'Bosan Road, Multan',
                'labs_count' => 3,
                'royalty_rate' => 18.00,
                'status' => 'active',
                'remarks' => 'Demo franchise with 18% royalty',
            ],
            [
                'name' => 'Career Institute Rawalpindi',
                'title' => 'Career Institute Rawalpindi',
                'slug' => 'career-institute-rawalpindi',
                'code' => 'CIRWP01',
                'country' => 'Pakistan',
                'city' => 'Rawalpindi',
                'city_abbr' => 'RWP',
                'campus_type' => 'company',
                'campus_email' => 'rawalpindi@career.test',
                'landline' => '051-3000-1005',
                'mobile' => '0300-0001005',
                'address' => 'Saddar, Rawalpindi',
                'labs_count' => 4,
                'royalty_rate' => null,
                'status' => 'active',
                'remarks' => 'Demo company campus',
            ],
            [
                'name' => 'Career Franchise Peshawar',
                'title' => 'Career Franchise Peshawar',
                'slug' => 'career-franchise-peshawar',
                'code' => 'CIPSW01',
                'country' => 'Pakistan',
                'city' => 'Peshawar',
                'city_abbr' => 'PSW',
                'campus_type' => 'franchise',
                'campus_email' => 'peshawar.franchise@career.test',
                'landline' => '091-3000-2004',
                'mobile' => '0301-0002004',
                'address' => 'University Road, Peshawar',
                'labs_count' => 2,
                'royalty_rate' => 15.00,
                'status' => 'active',
                'remarks' => 'Demo franchise with 15% royalty',
            ],
        ];

        foreach ($campuses as $campus) {
            Campus::updateOrCreate(
                ['code' => $campus['code']],
                array_merge(
                    $campus,
                    ['slug' => $campus['slug'] ?: Str::slug($campus['name'])]
                )
            );
        }
    }
}
