<?php

namespace Database\Seeders;

use App\Models\Lead;
use App\Models\User;
use App\Models\WebLead;
use Illuminate\Database\Seeder;

class WebLeadSeeder extends Seeder
{
    public function run(): void
    {
        $handledBy = User::query()->value('id');
        $convertedLeadId = Lead::query()->training()->value('id');

        $rows = [
            [
                'source_type' => WebLead::SOURCE_QUICK_LEAD,
                'full_name' => 'Areeba Khalid',
                'email' => 'areeba.khalid.weblead@career.test',
                'phone' => '0300-5550101',
                'country' => 'Pakistan',
                'city' => 'Lahore',
                'area' => 'Johar Town',
                'interested_program' => 'Full Stack Developer',
                'preferred_campus' => 'Lahore Main Campus',
                'teaching_method' => 'online',
                'gender' => 'female',
                'message' => 'Need weekend class details.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subMinutes(25),
            ],
            [
                'source_type' => WebLead::SOURCE_QUICK_LEAD,
                'full_name' => 'Hassan Raza',
                'email' => 'hassan.raza.weblead@career.test',
                'phone' => '0300-5550102',
                'country' => 'Pakistan',
                'city' => 'Faisalabad',
                'area' => 'Jinnah Colony',
                'interested_program' => 'Data Science',
                'preferred_campus' => 'Faisalabad Campus',
                'teaching_method' => 'campus',
                'gender' => 'male',
                'message' => 'Share fee structure and admission date.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subHours(2),
            ],
            [
                'source_type' => WebLead::SOURCE_QUICK_LEAD,
                'full_name' => 'Maria Aslam',
                'email' => 'maria.aslam.weblead@career.test',
                'phone' => '0300-5550103',
                'country' => 'Pakistan',
                'city' => 'Sialkot',
                'area' => 'Cantt',
                'interested_program' => 'Graphic Design Professional',
                'preferred_campus' => 'Sialkot Campus',
                'teaching_method' => 'hybrid',
                'gender' => 'female',
                'message' => 'Need timings for female evening batch.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subHours(5),
            ],
            [
                'source_type' => WebLead::SOURCE_WEBSITE_ENROLLMENT,
                'full_name' => 'Usman Tariq',
                'email' => 'usman.tariq.weblead@career.test',
                'phone' => '0300-5550201',
                'country' => 'Pakistan',
                'city' => 'Gujranwala',
                'area' => 'Satellite Town',
                'interested_program' => 'Digital Marketing Pro',
                'preferred_campus' => 'Gujranwala Campus',
                'teaching_method' => 'online',
                'gender' => 'male',
                'message' => 'Ready to enroll after counselor call.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subDay()->addHours(3),
            ],
            [
                'source_type' => WebLead::SOURCE_WEBSITE_ENROLLMENT,
                'full_name' => 'Nimra Saeed',
                'email' => 'nimra.saeed.weblead@career.test',
                'phone' => '0300-5550202',
                'country' => 'Pakistan',
                'city' => 'Lahore',
                'area' => 'Model Town',
                'interested_program' => 'QuickBooks for Accounts',
                'preferred_campus' => 'Lahore Main Campus',
                'teaching_method' => 'campus',
                'gender' => 'female',
                'message' => 'Need morning schedule before confirmation.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subDays(2),
            ],
            [
                'source_type' => WebLead::SOURCE_WEBSITE_ADMISSION,
                'full_name' => 'Bilal Ahmed',
                'email' => 'bilal.ahmed.weblead@career.test',
                'phone' => '0300-5550301',
                'country' => 'Pakistan',
                'city' => 'Faisalabad',
                'area' => 'People Colony',
                'interested_program' => 'Cyber Security Essentials',
                'preferred_campus' => 'Faisalabad Campus',
                'teaching_method' => 'campus',
                'gender' => 'male',
                'message' => 'Asked about admission form and documents.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subHours(8),
            ],
            [
                'source_type' => WebLead::SOURCE_WEBSITE_ADMISSION,
                'full_name' => 'Rabia Javed',
                'email' => 'rabia.javed.weblead@career.test',
                'phone' => '0300-5550302',
                'country' => 'Pakistan',
                'city' => 'Lahore',
                'area' => 'Wapda Town',
                'interested_program' => 'Full Stack Developer',
                'preferred_campus' => 'Lahore Main Campus',
                'teaching_method' => 'online',
                'gender' => 'female',
                'message' => 'Wants to start next month.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subDays(3)->addHours(2),
            ],
            [
                'source_type' => WebLead::SOURCE_BROCHURE_DOWNLOAD,
                'full_name' => 'Ali Hamza',
                'email' => 'ali.hamza.weblead@career.test',
                'phone' => '0300-5550401',
                'country' => 'Pakistan',
                'city' => 'Sargodha',
                'area' => 'University Road',
                'interested_program' => 'Graphic Design Professional',
                'preferred_campus' => 'Online',
                'teaching_method' => 'online',
                'gender' => 'male',
                'message' => 'Downloaded brochure and requested call back.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subMinutes(90),
            ],
            [
                'source_type' => WebLead::SOURCE_BROCHURE_DOWNLOAD,
                'full_name' => 'Iqra Noor',
                'email' => 'iqra.noor.weblead@career.test',
                'phone' => '0300-5550402',
                'country' => 'Pakistan',
                'city' => 'Multan',
                'area' => 'Gulgasht',
                'interested_program' => 'Digital Marketing Pro',
                'preferred_campus' => 'Online',
                'teaching_method' => 'hybrid',
                'gender' => 'female',
                'message' => 'Needs WhatsApp follow-up.',
                'status' => WebLead::STATUS_NEW,
                'submitted_at' => now()->subDays(4),
            ],
            [
                'source_type' => WebLead::SOURCE_QUICK_LEAD,
                'full_name' => 'Sana Mir',
                'email' => 'sana.mir.weblead@career.test',
                'phone' => '0300-5550501',
                'country' => 'Pakistan',
                'city' => 'Islamabad',
                'area' => 'G-11',
                'interested_program' => 'QuickBooks for Accounts',
                'preferred_campus' => 'Online',
                'teaching_method' => 'online',
                'gender' => 'female',
                'message' => 'No longer interested.',
                'status' => WebLead::STATUS_NOT_INTERESTED,
                'handled_by' => $handledBy,
                'handled_at' => now()->subDay(),
                'submitted_at' => now()->subDays(5),
            ],
            [
                'source_type' => WebLead::SOURCE_WEBSITE_ENROLLMENT,
                'full_name' => 'Farhan Malik',
                'email' => 'farhan.malik.weblead@career.test',
                'phone' => '0300-5550502',
                'country' => 'Pakistan',
                'city' => 'Lahore',
                'area' => 'Township',
                'interested_program' => 'Data Science',
                'preferred_campus' => 'Lahore Main Campus',
                'teaching_method' => 'campus',
                'gender' => 'male',
                'message' => 'Converted to CRM lead for testing.',
                'status' => $convertedLeadId ? WebLead::STATUS_LEAD_CREATED : WebLead::STATUS_NEW,
                'converted_to_lead_id' => $convertedLeadId,
                'handled_by' => $convertedLeadId ? $handledBy : null,
                'handled_at' => $convertedLeadId ? now()->subHours(10) : null,
                'submitted_at' => now()->subDays(6),
            ],
        ];

        foreach ($rows as $row) {
            WebLead::updateOrCreate(
                [
                    'source_type' => $row['source_type'],
                    'email' => $row['email'],
                ],
                [
                    ...$row,
                    'source_site' => 'career.edu.pk',
                    'payload' => [
                        'source_type' => $row['source_type'],
                        'name' => $row['full_name'],
                        'email' => $row['email'],
                        'phone' => $row['phone'],
                        'country' => $row['country'],
                        'city' => $row['city'],
                        'area' => $row['area'],
                        'program' => $row['interested_program'],
                        'campus' => $row['preferred_campus'],
                        'teaching_method' => $row['teaching_method'],
                        'gender' => $row['gender'],
                        'message' => $row['message'],
                    ],
                ]
            );
        }
    }
}
